name: Docker Image build and push

on:
  push:
    paths:
    - 'last_version.txt'
    - 'Dockerfile'
  workflow_dispatch:

jobs:
  path-context:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get sha
        id: get-sha
        run: echo ::set-output name=sha::$(curl -sL https://api.github.com/repos/Wind4/vlmcsd/branches/master | jq -r ".commit.sha" | cut -c1-7)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64/v8,linux/ppc64le,linux/s390x,linux/386,linux/arm/v7,linux/arm/v6
          push: true
          tags: tobsa/vlmcsd:latest,tobsa/vlmcsd:${{ steps.get-sha.outputs.sha }}
