name: Docker Image build and push

on:
  push:
    paths:
    - 'last_version.txt'
    - 'Dockerfile'
  workflow_dispatch:

jobs:
  path-context:
    name: Build and push
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get sha
        id: get-sha
        run: echo ::set-output name=sha::$(curl -sL https://api.github.com/repos/Wind4/vlmcsd/branches/master | jq -r ".commit.sha" | cut -c1-7)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm/v7
          push: true
          tags: |
          tobsa/vlmcsd:latest
          tobsa/vlmcsd:${{ steps.get-sha.sha }}